### PR TITLE
Automatic release workflow completed

### PR DESCRIPTION
**Pull request by marcelmmc**
Hi @johentsch, after taking in consideration the feedback. I think this version could be merged to the main branch. Nevertheless, There are couple of things that needs to be mentioned for this PR: 

- Rather than using the https://github.com/marketplace/actions/automatic-releases, I swapped the action with  https://github.com/marketplace/actions/create-release, the main reason for this decision is that automatic releases requires some changes to its source,  there has not been much support for two years, and the mechanism to create the action in the marketplace is a bit ambiguous. 

- For the zenodo and citation files, there are two ways in which we could replace the tags, which one would you prefer?
  - The old tag is used to replace strings in the files 
   - Using a regex with pattern ```v\d+\.(\d+\.\d+|\d+)``` to replace strings in the files
   
   Notice: the advantage of using regex is that for any string version which is not the latest tag, these will still update with the new tag

- It does not seem possible to update the zenodo and citation files when the PR is being merged, a simple solution is to push these changes to the main branch once the PR is merged, what do you think about this? 

- When applying transform, should we commit and push the generated files ?

### CODE REVIEW

**Comment by johentsch** [comment]
Thanks a lot!

>     * For the zenodo and citation files, there are two ways in which we could replace the tags, which one would you prefer?
>       
>       * The old tag is used to replace strings in the files
>       * Using a regex with pattern `v\d+\.(\d+\.\d+|\d+)` to replace strings in the files

Please do the former, via exact string matching. Otherwise we cannot mention older versions  in the README, for example.

>     * It does not seem possible to update the zenodo and citation files when the PR is being merged, a simple solution is to push these changes to the main branch once the PR is merged, what do you think about this?

OK if I understand correctly the order of events as follows:

* merge
* update files & push
* create tag & release

>     * When applying transform, should we commit and push the generated files ?

No.

**Comment by marcelmmc** [comment]
Thanks @johentsch, the modifications for the workflow have been pushed.

**Comment by johentsch** [comment]
Amazing, trying it out now, thank you!

Do we currently have a mechanism for going to the next major version? Like, in the marketplace action we have seen, they use particular labels such as `major` as a signal, but any other solution, e.g. involving manual tag assignment, would be good, too.

**Comment by johentsch** [comment]
So we tested the latest version of the version_release [here](https://github.com/DCMLab/bach_solo/releases/tag/v2.2) and there was a glitch. 

The two latest tags had been `v2.0` and `v2.1` but the action created a release pointing to `v2.0` instead of correctly creating the new tag `v2.2` (I've corrected that manually). Could you please check? The reason is obviously that this was the first release on this repo, but the action should be finding the latest tag even if no release is attached to it. Is it maybe because of the change that I had done to the code, putting in `v2.0` as the default value?

**Comment by marcelmmc** [comment]
The workflow was getting the latest tag release,  now it should retrieve the latest tag. In addition, a label named ```major_version``` can be attached to the PR to update the major version part of the tag. Note that when updating the major version, minor version returns to zero. For instance, 2.20 -> 3.0

**Review by johentsch — APPROVED** [review]
Nice, @marcelmmc, let's try it out then.

**Pull request merged**
